const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function harness(initial={},extra={}){const records=new Map(Object.entries(initial));const api={};let lookups=0;const db={doc:p=>({path:p}),collection:name=>({where:(_f,_op,c)=>({limit:()=>({name,c})})}),runTransaction:async fn=>fn({get:async ref=>{if(ref.name){const docs=Object.entries(extra[ref.name]||{}).filter(([,v])=>v.campaignId===ref.c).map(([id,v])=>({id,data:()=>v}));return {size:docs.length,docs};}return {exists:records.has(ref.path),data:()=>records.get(ref.path)};},create:(r,v)=>records.set(r.path,v)})};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../functions/leader-panel.cjs'),'utf8'),{exports:api,require:n=>n.includes('firebase-functions')?{onCall:(_o,f)=>f,HttpsError:class extends Error{constructor(c,m){super(m);this.code=c;}}}:n.includes('firestore')?{getFirestore:()=>db}:{getAuth:()=>({getUser:async()=>{lookups++;return {email:'leader@example.test'};}})},Date,Map,Set});return {api,records,lookups:()=>lookups};}
const admin={role:'admin',active:true,campaignId:'A'};const leader={role:'lider_principal',active:true,campaignId:'A'};
test('anonymous rejected',async()=>{await assert.rejects(harness().api.getPrincipalLeaderPanel({}),e=>e.code==='unauthenticated');});
test('municipal coordinator cannot access direction or assign',async()=>{const h=harness({'usuarios/u':{...admin,role:'coordinador_municipal'}});for(const f of ['getPrincipalLeaderPanel','assignPrincipalLeader'])await assert.rejects(h.api[f]({auth:{uid:'u'},data:{uid:'new',name:'Leader'}}),e=>e.code==='permission-denied');assert.equal(h.lookups(),0);});
test('inactive leader rejected',async()=>{await assert.rejects(harness({'usuarios/u':{...leader,active:false}}).api.getPrincipalLeaderPanel({auth:{uid:'u'}}));});
test('role alone does not authorize unregistered leader',async()=>{await assert.rejects(harness({'usuarios/u':leader,'principalLeaders/A':{uid:'other'}}).api.getPrincipalLeaderPanel({auth:{uid:'u'}}));});
test('new leader assigned once; repeated same request idempotent',async()=>{const h=harness({'usuarios/admin':admin});const r={auth:{uid:'admin'},data:{uid:'new',name:'Leader'}};await h.api.assignPrincipalLeader(r);await h.api.assignPrincipalLeader(r);assert.equal(h.records.get('principalLeaders/A').uid,'new');assert.equal(h.records.get('usuarios/new').role,'lider_principal');await assert.rejects(h.api.assignPrincipalLeader({...r,data:{uid:'other',name:'Other'}}),e=>e.code==='already-exists');});
test('existing hierarchy profile cannot be converted',async()=>{const h=harness({'usuarios/admin':admin,'usuarios/old':{role:'integrante'}});await assert.rejects(h.api.assignPrincipalLeader({auth:{uid:'admin'},data:{uid:'old',name:'Leader'}}),e=>e.code==='failed-precondition');assert.equal(h.records.get('usuarios/old').role,'integrante');});
test('campaign isolation and unique evidence count',async()=>{const h=harness({'usuarios/u':leader,'principalLeaders/A':{uid:'u'}},{municipios:{m:{campaignId:'A',id:'M',name:'Municipio'},foreign:{campaignId:'B',id:'B'}},usuarios:{person:{campaignId:'A',municipalityId:'M',role:'participante'}},misiones:{one:{campaignId:'A',assignedTo:'person'},two:{campaignId:'A',assignedTo:'person'},foreign:{campaignId:'B',assignedTo:'person'}},missionEvidence:{a:{campaignId:'A',missionId:'one',uploadedBy:'person'},b:{campaignId:'A',missionId:'one',uploadedBy:'person'},forged:{campaignId:'A',missionId:'two',uploadedBy:'other'}}});const r=await h.api.getPrincipalLeaderPanel({auth:{uid:'u'}});assert.equal(r.municipalities.length,1);assert.equal(r.municipalities[0].total,2);assert.equal(r.municipalities[0].withEvidence,1);assert.equal(r.municipalities[0].percentage,50);});

test('unassigned missions separated from unresolved recipients and municipal progress',()=>{const {api}=harness();const r=api._buildPanel([{id:'M',name:'Municipio'}],[{_id:'person',municipalityId:'M'}],[],[{_id:'old',brigadeId:'B'},{_id:'blank',assignedTo:''},{_id:'null',assignedTo:null},{_id:'unknown',assignedTo:'missing'},{_id:'valid',assignedTo:'person'}],[{missionId:'valid',uploadedBy:'person'}]);assert.equal(r.unassignedMissions,3);assert.equal(r.unmatchedMissions,1);assert.equal(r.municipalities[0].total,1);assert.equal(r.municipalities[0].withEvidence,1);assert.equal(r.municipalities[0].percentage,100);});
