const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(profile,lock,rows=[],size=rows.length){const api={};let reads=0;const db={doc:path=>({path}),collection:()=>({where:(field,op,campaign)=>{assert.equal(field,'campaignId');assert.equal(campaign,'A');return {limit:()=>({query:true})};}}),runTransaction:fn=>fn({get:async ref=>ref.query?(reads++,{size,docs:rows.filter(v=>v.campaignId==='A').map(v=>({data:()=>v}))}):{data:()=>ref.path.startsWith('usuarios/')?profile:lock}})};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../functions/leader-territory.cjs'),'utf8'),{exports:api,require:n=>n.includes('firebase-functions')?{onCall:(_,fn)=>fn,HttpsError:class extends Error{constructor(c,m){super(m);this.code=c;}}}:{getFirestore:()=>db},Date,Intl,Map,Set});return {api,reads:()=>reads};}
const p={active:true,role:'lider_principal',campaignId:'A'},r={auth:{uid:'u'},data:{}};
const stamp=s=>({toDate:()=>new Date(s)});
test('access rejects anonymous, inactive, coordinator and unregistered leader before visits',async()=>{for(const [profile,lock,req] of [[p,{uid:'u'},{}],[{...p,active:false},{uid:'u'},r],[{...p,role:'coordinador_municipal'},{uid:'u'},r],[p,{uid:'other'},r]]){const h=harness(profile,lock);await assert.rejects(h.api.getPrincipalLeaderTerritory(req));assert.equal(h.reads(),0);}});
test('campaign isolation, revisits, unknown addresses, private fields excluded and date boundary',async()=>{const rows=[{campaignId:'A',locality:'Tepic',normalizedAddress:'CALLE 1',interviewerId:'x',flyerDelivered:true,createdAt:stamp('2026-09-09T04:00:00Z'),citizenName:'PRIVATE',votingIntention:'PRIVATE'},{campaignId:'A',locality:'Tepic',normalizedAddress:'calle 1',interviewerId:'x',createdAt:stamp('2026-09-09T05:00:00Z')},{campaignId:'A',locality:'Tepic'},{campaignId:'B',locality:'Foreign'}];const h=harness(p,{uid:'u'},rows);const d=await h.api.getPrincipalLeaderTerritory(r);assert.equal(d.visits,3);assert.equal(d.identifiedHomes,1);assert.equal(d.unknownAddress,1);assert.equal(d.flyerVisits,1);assert.equal(d.activeReporters,1);assert.equal(d.daily[0].date,'2026-09-08');assert.ok(!JSON.stringify(d).includes('PRIVATE'));const filtered=await h.api.getPrincipalLeaderTerritory({...r,data:{from:'2026-09-08',to:'2026-09-08',locality:'Tepic'}});assert.equal(filtered.visits,2);assert.equal(filtered.undatedTotal,1);});
test('invalid dates and truncation fail explicitly',async()=>{const h=harness(p,{uid:'u'},[],10001);await assert.rejects(h.api.getPrincipalLeaderTerritory(r),e=>e.code==='resource-exhausted');for(const data of [{from:'2026-02-30'},{from:'2026-09-10',to:'2026-09-01'}])await assert.rejects(h.api.getPrincipalLeaderTerritory({...r,data}),e=>e.code==='invalid-argument');});
test('empty campaign and authorized admin',async()=>{const h=harness({...p,role:'admin'},null);const d=await h.api.getPrincipalLeaderTerritory(r);assert.equal(d.visits,0);assert.equal(d.identifiedHomes,0);});
test('map contains only valid coordinates from filtered campaign visits',async()=>{const rows=[{campaignId:'A',locality:'Uno',hasLocation:true,latitude:21,longitude:-105,citizenName:'SECRET',createdAt:stamp('2026-09-09T15:00:00Z')},{campaignId:'A',locality:'Uno',hasLocation:true,latitude:91,longitude:0},{campaignId:'A',locality:'Uno',hasLocation:false,latitude:21,longitude:-105},{campaignId:'A',locality:'Dos',hasLocation:true,latitude:22,longitude:-105},{campaignId:'B',locality:'Uno',hasLocation:true,latitude:23,longitude:-105}];const h=harness(p,{uid:'u'},rows);const d=await h.api.getPrincipalLeaderTerritory({...r,data:{locality:'Uno'}});assert.equal(d.points.length,1);assert.equal(d.withoutLocation,2);assert.equal(JSON.stringify(d.points),'[{"lat":21,"lng":-105}]');const f=await h.api.getPrincipalLeaderTerritory({...r,data:{from:'2026-09-10'}});assert.equal(f.points.length,0);});
