const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const adminCampaignAccess=require('../functions/admin-campaign-access.cjs');
function harness(initial={},extra={}){const records=new Map(Object.entries(initial));const api={};let lookups=0;const db={doc:p=>({path:p}),collection:name=>({where:(_f,_op,c)=>({limit:()=>({name,c})})}),runTransaction:async fn=>fn({get:async ref=>{if(ref.name){const docs=Object.entries(extra[ref.name]||{}).filter(([,v])=>v.campaignId===ref.c).map(([id,v])=>({id,data:()=>v}));return {size:docs.length,docs};}return {exists:records.has(ref.path),data:()=>records.get(ref.path)};},create:(r,v)=>records.set(r.path,v)})};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../functions/leader-panel.cjs'),'utf8'),{exports:api,require:n=>n==='./admin-campaign-access.cjs'?adminCampaignAccess:n.includes('firebase-functions')?{onCall:(_o,f)=>f,HttpsError:class extends Error{constructor(c,m){super(m);this.code=c;}}}:n.includes('firestore')?{getFirestore:()=>db}:{getAuth:()=>({getUser:async()=>{lookups++;return {email:'leader@example.test'};}})},Date,Map,Set});return {api,records,lookups:()=>lookups};}
const admin={role:'admin',active:true,campaignId:'A'};const leader={role:'lider_principal',active:true,campaignId:'A'};
test('anonymous rejected',async()=>{await assert.rejects(harness().api.getPrincipalLeaderPanel({}),e=>e.code==='unauthenticated');});
test('municipal coordinator cannot access direction or assign',async()=>{const h=harness({'usuarios/u':{...admin,role:'coordinador_municipal'}});for(const f of ['getPrincipalLeaderPanel','assignPrincipalLeader'])await assert.rejects(h.api[f]({auth:{uid:'u'},data:{campaignId:'A',uid:'new',name:'Leader'}}),e=>e.code==='permission-denied');assert.equal(h.lookups(),0);});
test('inactive leader rejected',async()=>{await assert.rejects(harness({'usuarios/u':{...leader,active:false}}).api.getPrincipalLeaderPanel({auth:{uid:'u'}}));});
test('role alone does not authorize unregistered leader',async()=>{await assert.rejects(harness({'usuarios/u':leader,'principalLeaders/A':{uid:'other'}}).api.getPrincipalLeaderPanel({auth:{uid:'u'}}));});
test('new leader assigned once; repeated same request idempotent',async()=>{const h=harness({'usuarios/admin':admin,'campaigns/A':{campaignId:'A',active:true}});const r={auth:{uid:'admin'},data:{campaignId:'A',uid:'new',name:'Leader'}};const first=await h.api.assignPrincipalLeader(r);const second=await h.api.assignPrincipalLeader(r);assert.equal(first.alreadyAssigned,false);assert.equal(second.alreadyAssigned,true);assert.equal(h.records.get('principalLeaders/A').uid,'new');assert.equal(h.records.get('usuarios/new').role,'lider_principal');await assert.rejects(h.api.assignPrincipalLeader({...r,data:{campaignId:'A',uid:'other',name:'Other'}}),e=>e.code==='already-exists');});
test('existing hierarchy profile cannot be converted',async()=>{const h=harness({'usuarios/admin':admin,'campaigns/A':{campaignId:'A',active:true},'usuarios/old':{role:'integrante'}});await assert.rejects(h.api.assignPrincipalLeader({auth:{uid:'admin'},data:{campaignId:'A',uid:'old',name:'Leader'}}),e=>e.code==='failed-precondition');assert.equal(h.records.get('usuarios/old').role,'integrante');});
test('admin must provide campaignId when assigning leader',async()=>{const h=harness({'usuarios/admin':admin});await assert.rejects(h.api.assignPrincipalLeader({auth:{uid:'admin'},data:{uid:'new',name:'Leader'}}),e=>e.code==='invalid-argument');assert.equal(h.lookups(),0);});
test('admin cannot assign leader to nonexistent campaign',async()=>{const h=harness({'usuarios/admin':admin});await assert.rejects(h.api.assignPrincipalLeader({auth:{uid:'admin'},data:{campaignId:'B',uid:'new',name:'Leader'}}),e=>e.code==='failed-precondition');assert.equal(h.lookups(),0);});
test('admin cannot assign leader to formal campaign without access',async()=>{const h=harness({'usuarios/admin':admin,'campaigns/B':{campaignId:'B',active:true}});await assert.rejects(h.api.assignPrincipalLeader({auth:{uid:'admin'},data:{campaignId:'B',uid:'new',name:'Leader'}}),e=>e.code==='permission-denied');assert.equal(h.lookups(),0);});
test('admin can assign leader to second campaign with explicit access',async()=>{const h=harness({'usuarios/admin':admin,'campaigns/B':{campaignId:'B',active:true},'adminCampaignAccess/admin/campaigns/B':{adminUid:'admin',campaignId:'B',active:true}});const r=await h.api.assignPrincipalLeader({auth:{uid:'admin'},data:{campaignId:'B',uid:'new-b',name:'Leader B'}});assert.equal(r.campaignId,'B');assert.equal(h.records.get('principalLeaders/B').uid,'new-b');assert.equal(h.records.get('usuarios/new-b').campaignId,'B');});
test('admin panel keeps legacy campaign when campaignId is omitted',async()=>{const h=harness({'usuarios/admin':admin,'campaigns/A':{campaignId:'A',active:true}},{municipios:{a:{campaignId:'A',id:'A-M',name:'Municipio A'},b:{campaignId:'B',id:'B-M',name:'Municipio B'}}});const r=await h.api.getPrincipalLeaderPanel({auth:{uid:'admin'},data:{}});assert.equal(r.campaignId,'A');assert.equal(r.municipalities.length,1);assert.equal(r.municipalities[0].name,'Municipio A');});
test('admin can inspect second campaign with explicit access',async()=>{const h=harness({'usuarios/admin':admin,'campaigns/B':{campaignId:'B',active:true},'adminCampaignAccess/admin/campaigns/B':{adminUid:'admin',campaignId:'B',active:true}},{municipios:{a:{campaignId:'A',id:'A-M',name:'Municipio A'},b:{campaignId:'B',id:'B-M',name:'Municipio B'}}});const r=await h.api.getPrincipalLeaderPanel({auth:{uid:'admin'},data:{campaignId:'B'}});assert.equal(r.campaignId,'B');assert.equal(r.municipalities.length,1);assert.equal(r.municipalities[0].name,'Municipio B');});

test('admin can inspect authorized empty campaign without principal leader',async()=>{const h=harness({'usuarios/admin':admin,'campaigns/C':{campaignId:'C',active:true},'adminCampaignAccess/admin/campaigns/C':{adminUid:'admin',campaignId:'C',active:true}});const r=await h.api.getPrincipalLeaderPanel({auth:{uid:'admin'},data:{campaignId:'C'}});assert.equal(r.campaignId,'C');assert.equal(r.municipalities.length,0);assert.equal(r.unassignedMissions,0);assert.equal(r.unmatchedMissions,0);assert.equal(h.records.has('principalLeaders/C'),false);});
test('admin cannot inspect second campaign without access',async()=>{const h=harness({'usuarios/admin':admin,'campaigns/B':{campaignId:'B',active:true}});await assert.rejects(h.api.getPrincipalLeaderPanel({auth:{uid:'admin'},data:{campaignId:'B'}}),e=>e.code==='permission-denied');});
test('principal leader ignores requested foreign campaign and remains in own campaign',async()=>{const h=harness({'usuarios/u':leader,'principalLeaders/A':{uid:'u'}},{municipios:{a:{campaignId:'A',id:'A-M',name:'Municipio A'},b:{campaignId:'B',id:'B-M',name:'Municipio B'}}});const r=await h.api.getPrincipalLeaderPanel({auth:{uid:'u'},data:{campaignId:'B'}});assert.equal(r.campaignId,'A');assert.equal(r.municipalities.length,1);assert.equal(r.municipalities[0].name,'Municipio A');});
test('campaign isolation and unique evidence count',async()=>{const h=harness({'usuarios/u':leader,'principalLeaders/A':{uid:'u'}},{municipios:{m:{campaignId:'A',id:'M',name:'Municipio'},foreign:{campaignId:'B',id:'B'}},usuarios:{person:{campaignId:'A',municipalityId:'M',role:'participante'}},misiones:{one:{campaignId:'A',assignedTo:'person'},two:{campaignId:'A',assignedTo:'person'},foreign:{campaignId:'B',assignedTo:'person'}},missionEvidence:{a:{campaignId:'A',missionId:'one',uploadedBy:'person'},b:{campaignId:'A',missionId:'one',uploadedBy:'person'},forged:{campaignId:'A',missionId:'two',uploadedBy:'other'}}});const r=await h.api.getPrincipalLeaderPanel({auth:{uid:'u'}});assert.equal(r.municipalities.length,1);assert.equal(r.municipalities[0].total,2);assert.equal(r.municipalities[0].withEvidence,1);assert.equal(r.municipalities[0].percentage,50);});

test('unassigned missions separated from unresolved recipients and municipal progress',()=>{const {api}=harness();const r=api._buildPanel([{id:'M',name:'Municipio'}],[{_id:'person',municipalityId:'M'}],[],[{_id:'old',brigadeId:'B'},{_id:'blank',assignedTo:''},{_id:'null',assignedTo:null},{_id:'unknown',assignedTo:'missing'},{_id:'valid',assignedTo:'person'}],[{missionId:'valid',uploadedBy:'person'}]);assert.equal(r.unassignedMissions,3);assert.equal(r.unmatchedMissions,1);assert.equal(r.municipalities[0].total,1);assert.equal(r.municipalities[0].withEvidence,1);assert.equal(r.municipalities[0].percentage,100);});
